services:

  db:
    image: mysql:latest
    container_name: app-data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - app-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    container_name: app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/app
    networks:
      - app-network

networks:
  app-network:


volumes:
  app-data:


