# Add your Powerlevel10k configuration here.
# This is just an example. You can generate your own configuration by running `p10k configure` in your terminal.
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%f'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{blue}❯%F{blue}❯%F{blue}❯%f '
POWERLEVEL9K_USER_ICON=''
POWERLEVEL9K_ROOT_ICON=''
POWERLEVEL9K_SUDO_ICON=''
POWERLEVEL9K_DIR_PATH_SEPARATOR='  '
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='blue'
POWERLEVEL9K_DIR_FOREGROUND='cyan'
POWERLEVEL9K_DIR_MAX_LENGTH=3
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='green'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND='yellow'
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND='yellow'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='blue'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='black'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND='black'
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND='black'
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='black'
